// Build-time sitemap generator.
//
// Reads teams / players / games / tournaments from Supabase (anon key) and
// writes public/sitemap.xml enumerating the static hubs plus every detail URL.
//
// Detail URLs are the Hebrew SLUG form only (/players/יואב-תורגמן), never the
// UUID form. The UUID URLs still work — api/resolve.js 308s them — but a
// sitemap must not list a URL that redirects, and listing both would ask
// Google to index one page twice.
//
// Resilience: any failure (network blip, missing creds) falls back to a
// hubs-only sitemap and the script ALWAYS exits 0 — a Supabase hiccup must
// never break `vite build`. Run standalone with `npm run gen:sitemap`.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const OUT = resolve(ROOT, 'public/sitemap.xml')

// --- env: prefer process.env (Vercel), fall back to the gitignored .env ---
function loadEnv() {
  const env = { ...process.env }
  if (env.VITE_SUPABASE_URL && env.VITE_SUPABASE_ANON_KEY) return env
  try {
    const raw = readFileSync(resolve(ROOT, '.env'), 'utf8')
    for (const line of raw.split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i)
      if (m && !line.trim().startsWith('#')) {
        const key = m[1]
        if (!(key in env)) env[key] = m[2].replace(/^["']|["']$/g, '')
      }
    }
  } catch { /* no .env — fine, we'll use whatever process.env has */ }
  return env
}

const env = loadEnv()
const SITE_URL = (env.VITE_SITE_URL || 'https://rinkhockeyil.com').replace(/\/$/, '')
const SUPABASE_URL = env.VITE_SUPABASE_URL
const ANON = env.VITE_SUPABASE_ANON_KEY

// Static hubs (host-relative path, changefreq, priority).
const HUBS = [
  ['/', 'daily', '1.0'],
  ['/standings', 'daily', '0.9'],
  ['/games', 'daily', '0.9'],
  ['/statistics', 'daily', '0.8'],
  ['/teams', 'weekly', '0.8'],
  ['/players', 'weekly', '0.8'],
  ['/media', 'weekly', '0.6'],
  ['/tournaments', 'weekly', '0.5'],
  ['/guide', 'monthly', '0.4'],
  ['/app', 'monthly', '0.4'],
  ['/archive', 'monthly', '0.5'],
  ['/privacy', 'yearly', '0.2'],
]

// The slug, falling back to the id for any row the trigger could not slug (a
// game with no date, say) — those keep their working UUID URL.
async function fetchKeys(table) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}?select=id,slug`, {
    headers: { apikey: ANON, authorization: `Bearer ${ANON}` },
  })
  if (!res.ok) throw new Error(`${table}: ${res.status} ${res.statusText}`)
  const rows = await res.json()
  return rows.map(r => r.slug || r.id).filter(Boolean)
}

function urlTag(path, changefreq, priority) {
  // Percent-encoded, to match what the app puts in <link rel=canonical> and
  // what og:url reports. Two spellings of one Hebrew URL read as two pages.
  const loc = `${SITE_URL}${path}`
  const extra = changefreq ? `<changefreq>${changefreq}</changefreq>` : ''
  const prio = priority ? `<priority>${priority}</priority>` : ''
  return `  <url><loc>${loc}</loc>${extra}${prio}</url>`
}

function write(urls, dynamicCount) {
  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/gen-sitemap.mjs — do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urls,
    '</urlset>',
    '',
  ].join('\n')
  mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, xml)
  console.log(`[gen-sitemap] wrote ${urls.length} URLs (${HUBS.length} hubs + ${dynamicCount} detail pages) → public/sitemap.xml @ ${SITE_URL}`)
}

async function main() {
  const urls = HUBS.map(([p, c, pr]) => urlTag(p, c, pr))

  if (!SUPABASE_URL || !ANON) {
    console.warn('[gen-sitemap] no Supabase creds — writing hubs-only sitemap.')
    write(urls, 0)
    return
  }

  try {
    const [teams, players, games, tournaments] = await Promise.all([
      fetchKeys('teams'), fetchKeys('players'), fetchKeys('games'), fetchKeys('tournaments'),
    ])
    const enc = encodeURIComponent
    for (const k of teams) urls.push(urlTag(`/teams/${enc(k)}`, 'weekly', '0.6'))
    for (const k of players) urls.push(urlTag(`/players/${enc(k)}`, 'weekly', '0.6'))
    for (const k of games) urls.push(urlTag(`/games/${enc(k)}`, 'monthly', '0.5'))
    for (const k of tournaments) urls.push(urlTag(`/tournaments/${enc(k)}`, 'monthly', '0.4'))
    write(urls, teams.length + players.length + games.length + tournaments.length)
  } catch (err) {
    console.warn(`[gen-sitemap] Supabase read failed (${err.message}) — writing hubs-only sitemap.`)
    write(urls, 0)
  }
}

// Never let a sitemap failure fail the build.
main().catch(err => {
  console.warn(`[gen-sitemap] unexpected error (${err?.message}) — skipping.`)
  process.exit(0)
})
