#!/usr/bin/env node
// Renders the Friday match-day poster from the weekly-preview function's facts.
//
//   node scripts/weekly-preview/render-poster.mjs <facts.json> <out.png>
//
// Drawn as HTML and screenshotted with headless Chrome rather than generated by an
// image model: an image model garbles Hebrew and invents crests, this uses the real
// crests from teams.logo_url and the real names, times and venue. 1600x900 because
// every feed card (web, iOS, Android) crops its image to 16:9.
//
// Fails (exit 1) instead of writing a poster with missing crests or a fallback font.
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import puppeteer from 'puppeteer'

const here = path.dirname(fileURLToPath(import.meta.url))
const W = 1600, H = 900

const [factsPath, outPath] = process.argv.slice(2)
if (!factsPath || !outPath) { console.error('usage: render-poster.mjs <facts.json> <out.png>'); process.exit(2) }

const raw = JSON.parse(await readFile(factsPath, 'utf8'))
const facts = raw.facts ?? raw
if (!facts.games?.length) { console.error('no games in facts — nothing to draw'); process.exit(1) }

const font = (await readFile(path.join(here, 'fonts/Heebo-Variable.ttf'))).toString('base64')
const logo = (await readFile(path.join(here, '../../public/logos/main-logo.png'))).toString('base64')

const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c])
const venues = [...new Set(facts.games.map((g) => g.venue).filter(Boolean))]
const oneVenue = venues.length === 1 ? venues[0] : null

const title = facts.is_opening_round ? 'פתיחת העונה' : 'מחזור השבת'
const kicker = facts.is_opening_round && facts.season ? `ליגת הוקי גלגיליות · עונת ${facts.season}` : 'ליגת הוקי גלגיליות'

const stageLabel = (g) => {
  if (g.game_type === 'פלייאוף') {
    const r = { first_round: 'רבע גמר', semi_final: 'חצי גמר', final: 'גמר', third_place: 'מקום 3', placement: 'משחק דירוג' }[g.playoff_round]
    return r ? `פלייאוף · ${r}${g.series_game ? ` · משחק ${g.series_game}` : ''}` : 'פלייאוף'
  }
  return g.game_type && g.game_type !== 'ליגה' ? g.game_type : null
}

const crest = (t) => t.logo_url
  ? `<div class="crest"><img src="${esc(t.logo_url)}" alt=""></div>`
  : `<div class="crest fallback" style="background:${esc(t.primary_color || '#1d4ed8')}">${esc([...t.name][0])}</div>`

const card = (g) => `
  <div class="card">
    <div class="time" dir="ltr">${esc(g.kickoff)}</div>
    ${stageLabel(g) ? `<div class="stage">${esc(stageLabel(g))}</div>` : ''}
    <div class="match">
      <div class="side">${crest(g.home)}<div class="name">${esc(g.home.name)}</div></div>
      <div class="vs">נגד</div>
      <div class="side">${crest(g.away)}<div class="name">${esc(g.away.name)}</div></div>
    </div>
    ${oneVenue ? '' : `<div class="venue">📍 ${esc(g.venue)}</div>`}
  </div>`

const html = `<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><style>
@font-face { font-family: Heebo; src: url(data:font/ttf;base64,${font}) format('truetype'); font-weight: 100 900; }
* { box-sizing: border-box; margin: 0; }
html, body { width: ${W}px; height: ${H}px; }
body {
  font-family: Heebo; color: #fff; overflow: hidden; position: relative;
  background: radial-gradient(ellipse 90% 70% at 50% 0%, #1e3f8a 0%, #0e2350 55%, #081634 100%);
}
/* rink markings, faint */
.rink { position: absolute; inset: 0; opacity: .09; }
.top { position: absolute; top: 44px; inset-inline: 64px; display: flex; align-items: center; gap: 28px; }
.top img { width: 108px; height: 108px; border-radius: 50%; object-fit: cover; box-shadow: 0 0 0 4px #e8b53a; }
.kicker { font-size: 30px; font-weight: 600; color: #e8b53a; letter-spacing: .5px; }
.title { font-size: 76px; font-weight: 900; line-height: 1; margin-top: 4px; }
.when { margin-inline-start: auto; text-align: left; }
.when .d { font-size: 54px; font-weight: 800; line-height: 1; }
.when .v { font-size: 30px; font-weight: 500; color: #c7d4f5; margin-top: 8px; }
.cards { position: absolute; top: 236px; bottom: 96px; inset-inline: 64px; display: flex; gap: 28px; }
.card {
  flex: 1; min-width: 0; border-radius: 28px; padding: 26px 22px 30px;
  background: linear-gradient(180deg, rgba(255,255,255,.11), rgba(255,255,255,.04));
  border: 2px solid rgba(255,255,255,.14);
  display: flex; flex-direction: column; align-items: center; justify-content: flex-start; padding-top: 52px;
}
.time { font-size: 64px; font-weight: 900; color: #e8b53a; line-height: 1; }
.stage { font-size: 24px; font-weight: 700; color: #c7d4f5; margin-top: 8px; }
.match { display: flex; align-items: flex-start; justify-content: center; gap: 10px; width: 100%; margin-top: 30px; }
.side { flex: 1; min-width: 0; display: flex; flex-direction: column; align-items: center; }
/* Crests arrive as circles, squares on white, transparent PNGs — one white disc makes them a set.
   16% padding keeps a square crest's corners inside the circle (inscribed square = 70.7%). */
.crest { width: 170px; height: 170px; border-radius: 50%; background: #fff; padding: 16%; flex-shrink: 0;
  display: flex; align-items: center; justify-content: center; box-shadow: 0 10px 26px rgba(0,0,0,.45), 0 0 0 4px rgba(255,255,255,.18); }
.crest img { width: 100%; height: 100%; object-fit: contain; }
.crest.fallback { padding: 0; color: #fff; font-size: 72px; font-weight: 900; }
.name { font-size: 38px; font-weight: 800; text-align: center; line-height: 1.1; margin-top: 18px; }
.vs { font-size: 30px; font-weight: 700; color: #8fa3d6; margin-top: 66px; }
.venue { font-size: 26px; color: #c7d4f5; margin-top: auto; }
.foot { position: absolute; bottom: 34px; inset-inline: 64px; display: flex; justify-content: space-between; font-size: 28px; color: #8fa3d6; font-weight: 500; }
.foot b { color: #fff; font-weight: 700; }
</style></head><body>
<svg class="rink" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">
  <line x1="${W / 2}" y1="0" x2="${W / 2}" y2="${H}" stroke="#fff" stroke-width="6"/>
  <circle cx="${W / 2}" cy="${H / 2}" r="190" fill="none" stroke="#fff" stroke-width="6"/>
  <path d="M0 250 A 250 250 0 0 1 0 650 M${W} 250 A 250 250 0 0 0 ${W} 650" fill="none" stroke="#fff" stroke-width="6"/>
</svg>
<div class="top">
  <img src="data:image/png;base64,${logo}" alt="">
  <div><div class="kicker">${esc(kicker)}</div><div class="title">${esc(title)}</div></div>
  <div class="when"><div class="d">יום ${esc(facts.date.day)} <span dir="ltr">${esc(facts.date.short)}</span></div>
    ${oneVenue ? `<div class="v">📍 ${esc(oneVenue)}</div>` : ''}</div>
</div>
<div class="cards">${facts.games.map(card).join('')}</div>
<div class="foot"><span>כל המשחקים, התוצאות והטבלה</span><b dir="ltr">rinkhockeyil.com</b></div>
</body></html>`

const browser = await puppeteer.launch({
  headless: true,
  args: ['--no-sandbox', '--disable-dev-shm-usage', '--font-render-hinting=none'],
  ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}),
})
try {
  const page = await browser.newPage()
  await page.setViewport({ width: W, height: H, deviceScaleFactor: 1 })
  await page.setContent(html, { waitUntil: 'networkidle0', timeout: 60_000 })
  const check = await page.evaluate(async () => {
    await document.fonts.ready
    const imgs = [...document.images]
    await Promise.all(imgs.map((i) => i.complete ? null : new Promise((r) => { i.onload = i.onerror = r })))
    return {
      font: document.fonts.check('900 40px Heebo'),
      broken: imgs.filter((i) => !i.naturalWidth).map((i) => i.src.slice(0, 120)),
      overflow: [...document.querySelectorAll('.name')].some((n) => n.scrollWidth > n.clientWidth + 2),
    }
  })
  if (!check.font) throw new Error('Heebo did not load — refusing to render Hebrew in a fallback font')
  if (check.broken.length) throw new Error(`crest(s) failed to load: ${check.broken.join(', ')}`)
  if (check.overflow) console.warn('warning: a team name overflows its card')
  await writeFile(outPath, await page.screenshot({ type: 'png' }))
  console.log(`poster → ${outPath} (${facts.games.length} games, ${facts.saturday})`)
} finally {
  await browser.close()
}
